language: c
os: linux
dist: bionic
compiler: gcc
install: make get-deps
jobs:
  include:
    - stage: test
      script: make test && ./test
    - stage: leak-check
      script: make spell_check && make test && valgrind --leak-check=full --errors-for-leak-kinds=all --error-exitcode=1 ./spell_check tests/samples/testcorpus.txt wordlist.txt && valgrind --leak-check=full --errors-for-leak-kinds=definite,indirect,possible --error-exitcode=1 ./test
